### ISSUE TITLE
Question on how to add Taggs to an EC2 Instance

### ISSUE THREAD

**Issue by jjdepaul** [treelogic-swe/aws-mock#59]
I want to launch a Mock EC2 image with several tags that are vital to my testing.   How can I add Tags to a Mock EC2 instance (either at launch or afterwards)?    TheMockEC2Controller.runInstances(...) method doesn't support adding Tags on startup.    Should I start the MockEC2Instance and then use the MockTagsController to createTags(...) on that instance?

**Comment by maxiaohao** [comment]
Hi jjdepaul,

Yes you may run mock instances and then call `create-tags` to add mock tags to those instances. `describe-tags` has been implemented so that you can fetch the mock tags you created. 

Please note tags on EC2 resources are not only for instances, but also for ami, volumes, etc. and this mock has been done separately in `MockTagsController`. So those mock tags created by `create-tags` are not accessible from other endpoints such as `describe-instances`. To achieve that you need to change the code in `MockEc2Controller` (a PR is welcomed). 

Hope that clarifies a bit for you. Thanks.

**Comment by nottoseethesun** [comment]
Seems like the question got answered very well.
